global class OmniDesignerOmniscriptInsertElementOutputRepresentation {
	global String name;
	global List<ConnectApi.OmniProcessInsertElementRepresentation> result;
	global OmniDesignerOmniscriptInsertElementOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}