global class OmniProcessInsertElementRepresentation {
	global String id;
	global Boolean isActive;
	global Integer level;
	global String name;
	global String omniProcessId;
	global String parentElementId;
	global String propertySetConfig;
	global Integer sequenceNumber;
	global String type;
	global OmniProcessInsertElementRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}