global class OmniProcessElementDeleteRepresentation {
	global String id;
	global String name;
	global String omniProcessId;
	global String parentElementId;
	global Integer sequenceNumber;
	global OmniProcessElementDeleteRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}