global class OmniDesignerOmniscriptMoveElementOutputRepresentation {
	global String elementName;
	global List<ConnectApi.OmniDesignerOmniProcessMoveElementRepresentation> results;
	global OmniDesignerOmniscriptMoveElementOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}