global class OmniDesignerOmniscriptDeleteElementOutputRepresentation {
	global List<ConnectApi.OmniProcessElementDeleteRepresentation> deleted;
	global String name;
	global List<ConnectApi.OmniProcessElementDeleteRepresentation> updated;
	global OmniDesignerOmniscriptDeleteElementOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}