global class RecordAggregationApplicableFieldOutputRepresentation {
	global String apiName;
	global String dataType;
	global Boolean isCompound;
	global String label;
	global RecordAggregationApplicableFieldOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}