global class RuleLibraryReadOutputRepresentation {
	global String apiName;
	global String contextDefinitionName;
	global String id;
	global String name;
	global ConnectApi.RuleLibraryVersionOutputRepresentationList ruleLibraryVersions;
	global ConnectApi.RuleLibraryStatusEnumRepresentation status;
	global String usageType;
	global RuleLibraryReadOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}