name: Close Production Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches:
      - master
    paths:
      - 'force-app/**'
jobs:
  merge_job:
    environment: production
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy on Production
      uses: jawills/sf-deploy@v1.0
      with:
        SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        DRY_RUN: false
        TEST_LEVEL: RunLocalTests

  close_job:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been closed without being merge